class Opportunity < ActiveRecord::Base
    belongs_to :user
    default_scope -> { order('created_at DESC') }

    scope :track,  ->(track)  { where(track: track.downcase)         }
    scope :city,   ->(city)   { where(location: city.downcase)       }
    scope :salary, ->(salary) { where("salary_low > ?", salary*1000) }

    before_save {
        downcase(:location=, self.location)
        downcase(:position=, self.position)
        downcase(:company=, self.company)
        downcase(:link=, self.link)
    }

    validates :user_id, :position, :company, :location, :track, presence: true

    validates :track, inclusion: { in: %w{dev sales product marketing}, 
        message: "%{value} is not a valid track" }

    validates :salary_low, :salary_high, numericality: true, presence: true

    private

    def downcase(setter, arg='')
        self.send(setter, arg.downcase! || arg)
    end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: opportunities
#
# * id          :integer         not null
#   position    :string(255)
#   company     :string(255)
#   location    :string(255)
#   contact     :string(255)
#   link        :text(255)
#   created_at  :datetime
#   updated_at  :datetime
#   track       :string(255)
#   user_id     :integer
#   notes       :text(255)
#   salary_low  :integer
#   salary_high :integer
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
