class Opportunity < ActiveRecord::Base
    belongs_to :user
    default_scope -> { order('created_at DESC') }
    validates :user_id, presence: true

    scope :track, lambda { |track| where(track: track.downcase) }
    scope :city, lambda { |city| where(location: city.downcase) }
    scope :salary, lambda { |salary| where("salary > ?", salary*1000) }
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: opportunities
#
# * id         :integer         not null
#   position   :string(255)
#   company    :string(255)
#   location   :string(255)
#   salary     :integer
#   contact    :string(255)
#   link       :string(255)
#   created_at :datetime
#   updated_at :datetime
#   track      :string(255)
#   user_id    :integer
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
