class User < ActiveRecord::Base
    has_many :opportunities
    
    def self.from_omniauth(auth)
        where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            user.url = auth.info.urls[:Facebook]
            user.img_url = auth.info.image
            user.oath_token = auth.credentials.oath_token
            user.oath_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: users
#
# * id              :integer         not null
#   uid             :string(255)
#   name            :string(255)
#   email           :string(255)
#   img_url         :string(255)
#   oath_token      :string(255)
#   oath_expires_at :datetime
#   created_at      :datetime
#   updated_at      :datetime
#   provider        :string(255)
#   url             :string(255)
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
